/**:
  ros__parameters:
    cmd_vel_stamped: true

    linear_velocity_factor:
      fast: 2.0
      regular: 0.5
      slow: 1.5

    angular_velocity_factor:
      fast: 1.88
      regular: 0.2
      slow: 0.3

    e_stop:
      present: false
      topic: hardware/e_stop
      reset_srv: hardware/e_stop_reset
      trigger_srv: hardware/e_stop_trigger

    # This button mapping should be common across all XInput controllers.
    # Input declaration consists of:
    # - optional negation '!',
    # - input type: 'A' for an axis or 'B' for a button,
    # - axis/button number.
    # A0 - D-pad left-right
    # A1 - D-pad up/down
    # A2 - LT and RT button
    # A3 - right joystick left/right
    # A4 - right joystick up/down
    # A6 - left joystick left/right
    # A7 - left joystick up/down
    input_index_map:
      axis:
        angular_z: 'A3' # Right joystick left/right
        linear_x: 'A1' # Left joystick left/right
        linear_y: 'A0' # Left joystick up/down
      dead_man_switch: 'B4' # LB
      fast_mode: '!A2' # RT (part of A2 axis)
      slow_mode: 'B5' # RB
      e_stop_reset: 'B0' # A
      e_stop_trigger: 'B1' # B
      enable_e_stop_reset: 'A2' # LT (part of A2 axis)
